language: csharp
sudo: false  # use the new container-based Travis infrastructure
dist: trusty

addons:
    apt:
        packages:
            - libunwind8

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 0.27.5
  - export PATH=$HOME/.yarn/bin:$PATH
cache:
  yarn: true

before_script:
  - nvm install 6.11
  - nvm use 6.11
  # Update npm
  - npm install -g npm

script:
  - ./build.sh All
